# Rustfmt configuration for Thrust
# See: https://rust-lang.github.io/rustfmt/

# Edition
edition = "2021"

# Line length
max_width = 100
comment_width = 80

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Formatting
use_small_heuristics = "Default"
fn_call_width = 80
struct_lit_width = 80
struct_variant_width = 80
array_width = 80
chain_width = 80

# Trailing comma
trailing_comma = "Vertical"
trailing_semicolon = true

# Misc
use_field_init_shorthand = true
use_try_shorthand = true
format_code_in_doc_comments = true
normalize_comments = true
wrap_comments = true
